package com.example.firebase;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;

import android.content.Context;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;

import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

public class CreateNoteActivity extends AppCompatActivity {
    private EditText etTitle, etDescription;
    private Button btnAdd;
    private FirebaseDatabase database;
    private DatabaseReference rootReference, noteReference, newNoteReference;
    private FirebaseUser currentUser;
    private CreateNoteActivity mContext;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_create_note);
        etTitle = findViewById(R.id.etTitle);
        etDescription = findViewById(R.id.etDescription);
        btnAdd = findViewById(R.id.btnAdd);
        btnAdd.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                putNoteInFirebase();
            }
        });

        mContext = CreateNoteActivity.this;
    }

    private void putNoteInFirebase() {

        currentUser = FirebaseAuth.getInstance().getCurrentUser();
        database = FirebaseDatabase.getInstance();
        rootReference = database.getReference(); // reference to database root reference.
        noteReference = rootReference.child("Users").child(currentUser.getUid()).child("Notes");//root/User/(current user Id)/Notes.
        newNoteReference = noteReference.push();
        Note newNote = new Note(etTitle.getText().toString(), etDescription.getText().toString());
        newNoteReference.setValue(newNote).addOnCompleteListener(new OnCompleteListener<Void>() {
            @Override
            public void onComplete(@NonNull Task<Void> task) {
                if (task.isSuccessful()){
                    Toast.makeText(CreateNoteActivity.this, "Note Created Successfully!", Toast.LENGTH_SHORT).show();
                    mContext.finish();
                }else {
                    Toast.makeText(CreateNoteActivity.this, "Something Went Wrong!", Toast.LENGTH_SHORT).show();
                }
            }
        });//root/User/(current user Id)/Notes/some random id generated by firebase.

    }
}